name: pgba
services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 30s
      timeout: 10s
      retries: 3  

  bot:
    build: .
    environment:
      ENV: prod
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      DESTINATION_EMAIL_ADDRESS: ${DESTINATION_EMAIL_ADDRESS}
      SMTP_EMAIL_ADDRESS: ${SMTP_EMAIL_ADDRESS}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      TOKEN: ${TOKEN}
    depends_on:
      selenium:
        condition: service_healthy